 name: Hello World Example

   on:
     push:
       branches: [ main ]

   jobs:
     hello_world_job:
       runs-on: ubuntu-latest
       steps:
         - name: Print a greeting
           run: echo "Hello, world! This is my first GitHub Action."
