# .github/workflows/print-message.yml
name: Print Message on Push or Pull Request

on: # 触发条件
  push: # 当有代码推送到仓库
  pull_request: # 或当有Pull Request提交时

jobs: # 定义任务
  print-message: # 任务名称
    runs-on: ubuntu-latest # 使用Ubuntu环境执行

    steps: # 执行步骤
    - name: Print Output # 打印输出信息
      run: |
        echo "代码库发生了变动！"
        echo "这是一次Push操作或Pull Request事件。"
