name: Daily Job at 1am

on:
  schedule:
    - cron: '22 22 * * *' # 每天凌晨1点执行（UTC时间）

jobs:
  daily-task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Print Current Time
      run: echo "当前时间：$(date)"